mode: 'train'
ARCHITECTURE:
    name: "MobileNetV3_large_x1_0"

pretrained_model: ""
model_save_dir: "./output/"
classes_num: 2
total_images: 800
save_interval: 10
ls_epsilon: 0.1
validate: True
valid_interval: 10
epochs: 301
topk: 2
image_shape: [3, 1440, 1440]

# mix数据预处理方法
use_mix: False
ls_epsilon: -1

LEARNING_RATE:
    function: 'Cosine'
    params:
        lr: 0.025
        warmup_epoch: 5

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.00001

TRAIN:
    batch_size: 16
    num_workers: 0
    file_list: "./dataset/常规赛：PALM病理性近视预测/train_list.txt"
    data_dir: "./dataset/常规赛：PALM病理性近视预测/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 1440
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:



VALID:
    batch_size: 16
    num_workers: 0
    file_list: "./dataset/常规赛：PALM病理性近视预测/val_list.txt"
    data_dir: "./dataset/常规赛：PALM病理性近视预测/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 1444
        - CropImage:
            size: 1440
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:




